config:
    RANDOM_SEED : 1111
    NUM_AREA : 2                         # number of meeting zone (2 persons can be enter is this zone)
    TIMEMEET : 10                        # minutes staying in the meeting zone
    SIM_TIME : 20000                     # Simulation time in minutes (in on cycle)
    NUM_PERSON : 10000                   # number of person in the simulation
    NUM_TIPS : 1000                      # number of object (person) go in meeting zone (in one cycle)
    NUM_CYCLE_OUTPUT : 100               # number of cycle
    P : 0.97                             # probability to infect someone